name: CI
on:
  schedule:
    - cron: "* 2 * * *"

jobs:
  generate_matrix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate matrix
        id: generate_matrix
        uses: ./.github/actions/matrix-generator

  build_images:
    runs-on: ubuntu-latest
    needs: [generate_matrix]
    strategy:
      matrix:
        # version: ${{ fromJson(needs.generate_matrix.outputs.matrix) }}
        version: ["3.6.13", "3.7.10", "3.8.9", "3.9.4"]
      # fail-fast: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            pipenv

      - name: Generate Python docker folders
        run: |
          pipenv install \
          && pipenv run python3 update.py
      
      - name: Build docker image
        run: |
          pushd docker/v${{ matrix.version }} \
          docker build . --tag giacomofurlan/python-precompiled:v${{ matrix.version }} \
          && popd
