name: CI
on:
  schedule:
    - cron: "29 22 * * *"

jobs:
  build_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      -name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install pipenv
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            pipenv

      - name: Generate Python docker folders
        run: |
          pipenv install \
          && pipenv run python3 update.py
      
      - name: Build docker image
        run: |
          for version in $(ls -1 docker); do \
            pushd docker/${version}; \
            docker build . --tag giacomofurlan/python-precompiled:$version; \
            docker push giacomofurlan/python-precompiled:$version; \
            popd; \
          done

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          author_email: giacomo+ci@giacomofurlan.name
          author_name: Giacomo Furlan (CI)
          message: Automated update of Dockerfiles
          branch: main
